#pragma once
#include <Windows.h>
#include <gl/GL.h>
#include "vendor/gl_defs/glcorearb.h"
#include "vendor/gl_defs/wglext.h"

#define X(proc, name) extern proc name

#define GLFUNCTIONS \
X(PFNGLGENBUFFERSPROC, glGenBuffers); \
X(PFNGLBINDBUFFERPROC, glBindBuffer); \
X(PFNGLBUFFERDATAPROC, glBufferData); \
X(PFNGLCREATESHADERPROC, glCreateShader); \
X(PFNGLSHADERSOURCEPROC, glShaderSource); \
X(PFNGLCOMPILESHADERPROC, glCompileShader); \
X(PFNGLGETSHADERIVPROC, glGetShaderiv); \
X(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog); \
X(PFNGLCREATEPROGRAMPROC, glCreateProgram); \
X(PFNGLATTACHSHADERPROC, glAttachShader); \
X(PFNGLLINKPROGRAMPROC, glLinkProgram); \
X(PFNGLGETPROGRAMIVPROC, glGetProgramiv); \
X(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog); \
X(PFNGLUSEPROGRAMPROC, glUseProgram); \
X(PFNGLDELETESHADERPROC, glDeleteShader); \
X(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer); \
X(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray); \
X(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays); \
X(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray); \
X(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation); \
X(PFNGLUNIFORM4FPROC, glUniform4f); \
X(PFNGLUNIFORM3FPROC, glUniform3f); \
X(PFNGLUNIFORM2FPROC, glUniform2f); \
X(PFNGLUNIFORM1FPROC, glUniform1f); \
X(PFNGLUNIFORM1IPROC, glUniform1i); \
X(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv); \
X(PFNGLACTIVETEXTUREPROC, glActiveTexture); \
X(PFNGLGENERATEMIPMAPPROC, glGenerateMipmap); \
X(PFNGLBUFFERSUBDATAPROC, glBufferSubData); \
X(PFNGLTEXSTORAGE3DPROC, glTexStorage3D); \
X(PFNGLTEXSUBIMAGE3DPROC, glTexSubImage3D); \
X(PFNGLDRAWARRAYSINSTANCEDPROC, glDrawArraysInstanced); \
X(PFNGLDRAWELEMENTSINSTANCEDPROC, glDrawElementsInstanced); \
X(PFNGLVERTEXATTRIBDIVISORPROC, glVertexAttribDivisor); \
X(PFNGLBINDBUFFERBASEPROC, glBindBufferBase); \
X(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers); \
X(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer); \
X(PFNGLFRAMEBUFFERTEXTURE2DPROC, glFramebufferTexture2D); \
X(PFNGLCHECKFRAMEBUFFERSTATUSPROC, glCheckFramebufferStatus); \
X(PFNGLDELETEFRAMEBUFFERSPROC, glDeleteFramebuffers); \
X(PFNWGLSwapINTERVALEXTPROC, wglSwapIntervalEXT); \
X(PFNGLDEBUGMESSAGECALLBACKPROC, glDebugMessageCallback); \
X(PFNGLDEBUGMESSAGECONTROLPROC, glDebugMessageControl); \
X(PFNGLGENRENDERBUFFERSPROC, glGenRenderbuffers); \
X(PFNGLBINDRENDERBUFFERPROC, glBindRenderbuffer); \
X(PFNGLRENDERBUFFERSTORAGEPROC, glRenderbufferStorage); \
X(PFNGLFRAMEBUFFERRENDERBUFFERPROC, glFramebufferRenderbuffer); \

GLFUNCTIONS
